// This file is automatically generated.
// Please do not edit this file manually.

#include "pch.h"
#include "ComponentRegister.h"
#include "EngineTester/ArrayTester.h"
#include "EngineTester/EasingTestComponent.h"
#include "EngineTester/MaterialTester.h"
#include "EngineTester/ReferenceTester.h"
#include "GameLib/Colliders/ConvexPolygonCollider2D.h"
#include "GameLib/Components/CatmullRomComponent.h"
#include "GameLib/Components/PathMover.h"
#include "GameLib/UI/Dialog.h"
#include "GameLib/UI/DialogController.h"
#include "GameLib/UI/PauseDialog.h"
#include "Game/ClearScene/SwingComponent.h"
#include "Game/Common/ChangeSceneComponent.h"
#include "Game/GamePlayScene/GameOverComponent.h"
#include "Game/GamePlayScene/PlaySceneManager.h"
#include "Game/SelectScene/SelectBlock.h"
#include "Game/TitleScene/TitleManager.h"
#include "Game/GamePlayScene/Camera/CameraCorrection.h"
#include "Game/GamePlayScene/Camera/ProjectionSmoothCamera.h"
#include "Game/GamePlayScene/Camera/StartCamera.h"
#include "Game/GamePlayScene/Camera/TPSCamera.h"
#include "Game/GamePlayScene/ChangeDimention/ChangeColliderComponent.h"
#include "Game/GamePlayScene/ChangeDimention/DepthCorrection.h"
#include "Game/GamePlayScene/ChangeDimention/DimentionManager.h"
#include "Game/GamePlayScene/Effect/ClearEffect.h"
#include "Game/GamePlayScene/Enemy/Enemy.h"
#include "Game/GamePlayScene/Enemy/EnemyManager.h"
#include "Game/GamePlayScene/Player/Player.h"
#include "Game/GamePlayScene/Stage/Components/GoalComponent.h"
#include "Game/GamePlayScene/Enemy/Components/LandingCandidatePoints.h"
#include "Game/GamePlayScene/Enemy/Components/LandingCandidatePoints2D.h"

void ComponentRegister::RegistComponents()
{
    REGIST_TO_FACTORY(ArrayTester);
    REGIST_TO_FACTORY(EasingTestComponent);
    REGIST_TO_FACTORY(MaterialTester);
    REGIST_TO_FACTORY(ReferenceTester);
    REGIST_TO_FACTORY(ConvexPolygonCollider2D);
    REGIST_TO_FACTORY(CatmullRomComponent);
    REGIST_TO_FACTORY(PathMover);
    REGIST_TO_FACTORY(Dialog);
    REGIST_TO_FACTORY(DialogController);
    REGIST_TO_FACTORY(PauseDialog);
    REGIST_TO_FACTORY(SwingComponent);
    REGIST_TO_FACTORY(ChangeSceneComponent);
    REGIST_TO_FACTORY(GameOverComponent);
    REGIST_TO_FACTORY(PlaySceneManager);
    REGIST_TO_FACTORY(SelectBlock);
    REGIST_TO_FACTORY(TitleManager);
    REGIST_TO_FACTORY(CameraCorrection);
    REGIST_TO_FACTORY(ProjectionSmoothCamera);
    REGIST_TO_FACTORY(StartCamera);
    REGIST_TO_FACTORY(TPSCamera);
    REGIST_TO_FACTORY(ChangeColliderComponent);
    REGIST_TO_FACTORY(DepthCorrection);
    REGIST_TO_FACTORY(DimentionManager);
    REGIST_TO_FACTORY(ClearEffect);
    REGIST_TO_FACTORY(Enemy);
    REGIST_TO_FACTORY(EnemyManager);
    REGIST_TO_FACTORY(Player);
    REGIST_TO_FACTORY(GoalComponent);
    REGIST_TO_FACTORY(LandingCandidatePoints);
    REGIST_TO_FACTORY(LandingCandidatePoints2D);
}
